[[redirects]]
  from = "/api/*"
  to = "https://mobillity-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://mobillity-api.onrender.com/auth/:splat"
  status = 200
  force = true
